# Example config for dogfooding moleman with Codex.
version: 1

steps:
  codex_write:
    type: run
    run: "mkdir -p .moleman/tmp && codex exec --full-auto {{ shellEscape (printf \"%s\\n\\nDo not offer next steps or additional tasks; just return the requested output.\" .input.prompt) }} --output-last-message .moleman/tmp/codex_write_last.txt"
    timeout: 45m
    capture: [stdout, stderr, exitCode]

  show_codex_write_last:
    type: run
    run: "(cat .moleman/tmp/codex_write_last.txt 2>/dev/null || true)"
    print: [stdout]

  prep_review:
    type: run
    run: "mkdir -p .moleman/tmp"

  codex_review:
    type: run
    run: "codex exec {{ shellEscape (printf \"Review only the changes not yet committed (the current git diff), and list must-fix issues. Your output will be fed directly to another agent. Do not offer next steps or additional tasks.\\n\\nOriginal prompt that produced this diff (for context):\\n%s\" .input.prompt) }} --output-last-message .moleman/tmp/review.txt"
    timeout: 30m
    capture: [stdout, stderr, exitCode]

  show_codex_review_last:
    type: run
    run: "(cat .moleman/tmp/review.txt 2>/dev/null || true)"
    print: [stdout]
    capture: [stdout, stderr, exitCode]

  codex_apply_review:
    type: run
    run: "{ printf 'Apply the review feedback below. Only change what is required. Do not offer next steps or additional tasks.\\n\\n'; cat .moleman/tmp/review.txt; } | codex exec --full-auto --output-last-message .moleman/tmp/codex_apply_review_last.txt"
    timeout: 45m
    capture: [stdout, stderr, exitCode]

  show_codex_apply_review_last:
    type: run
    run: "(cat .moleman/tmp/codex_apply_review_last.txt 2>/dev/null || true)"
    print: [stdout]
    capture: [stdout, stderr, exitCode]

  test:
    type: run
    run: "make check"
    timeout: 20m

  build:
    type: run
    run: "make build"
    timeout: 10m

groups:
  dogfood:
    - type: ref
      id: codex_write
    - type: ref
      id: show_codex_write_last
    - type: ref
      id: prep_review
    - type: ref
      id: codex_review
    - type: ref
      id: show_codex_review_last
    - type: ref
      id: codex_apply_review
    - type: ref
      id: show_codex_apply_review_last
    - type: ref
      id: test
    - type: ref
      id: build

pipelines:
  default:
    plan:
      - type: ref
        id: dogfood
