version: 1

# Example: Codex writes, Claude reviews, Codex fixes, Claude re-reviews.
# Notes:
# - Claude's /review-self is interactive-only; in non-interactive mode we use -p
#   and a review prompt instead.
# - Claude runs with --output-format json so we can capture session_id and
#   structured_output for loop control.
# - Codex fixes are applied in the SAME session via `codex exec resume --last`.

steps:
  codex_write:
    type: run
    run: "codex exec --full-auto {{ shellEscape .input.prompt }}"
    timeout: 45m
    capture: [stdout, stderr, exitCode]

  claude_review:
    type: run
    run: "claude -p {{ shellEscape (printf \"Review only the changes not yet committed (current git diff). Return must-fix issues as structured_output.\\n\\nOriginal prompt:\\n%s\" .input.prompt) }} --output-format json --json-schema '{\"type\":\"object\",\"properties\":{\"must_fix_count\":{\"type\":\"integer\"},\"must_fix_items\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"notes\":{\"type\":\"string\"}},\"required\":[\"must_fix_count\",\"must_fix_items\"],\"additionalProperties\":false}' --allowedTools \"Bash(git diff *),Bash(git status *),Read\""
    parse:
      kind: json
      into: claude_review
    timeout: 30m
    capture: [stdout, stderr, exitCode]

  codex_fix:
    type: run
    run: "codex exec resume --last --full-auto {{ shellEscape (printf \"Apply the review feedback below. If anything is not fixed, explain why.\\n\\n%s\" .vars.claude_review.result) }}"
    timeout: 45m
    capture: [stdout, stderr, exitCode]

  claude_rereview:
    type: run
    run: "claude -p {{ shellEscape (printf \"Re-review the current git diff. If issues remain, list must-fix items. Context from last fix attempt:\\n%s\" .steps.codex_fix.stdout) }} --output-format json --json-schema '{\"type\":\"object\",\"properties\":{\"must_fix_count\":{\"type\":\"integer\"},\"must_fix_items\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},\"notes\":{\"type\":\"string\"}},\"required\":[\"must_fix_count\",\"must_fix_items\"],\"additionalProperties\":false}' --resume {{ shellEscape .vars.claude_review.session_id }} --allowedTools \"Bash(git diff *),Bash(git status *),Read\""
    parse:
      kind: json
      into: claude_rereview
    timeout: 30m
    capture: [stdout, stderr, exitCode]

pipelines:
  codex-claude-loop:
    plan:
      - type: ref
        id: codex_write
      - type: ref
        id: claude_review
      - type: loop
        maxIters: 2
        until: "vars.claude_rereview.structured_output.must_fix_count == 0"
        body:
          - type: ref
            id: codex_fix
          - type: ref
            id: claude_rereview
